In [4]:

import pandas as pd
import numpy as np



df_hospital_2 = pd.read_csv('https://raw.githubusercontent.com/hantswilliams/AHI_STATS_507/main/Week13_Summary/output/df_hospital_2.csv')

ValueError: ignored

In [5]:
df_hospital_2

     provider_id  ...                              location
0         310119  ...            POINT (-74.19213 40.74095)
1         310016  ...  POINT (-74.05014200000001 40.734876)
2         390123  ...          POINT (-75.611502 40.243941)
3         440002  ...           POINT (-88.831973 35.63954)
4         330080  ...          POINT (-73.924072 40.817681)
...          ...  ...                                   ...
5309      49001F  ...          POINT (-77.142608 38.705877)
5310      26002F  ...          POINT (-92.116491 37.766471)
5311      50014F  ...         POINT (-122.680142 48.336875)
5312      21007F  ...           POINT (-77.096801 38.99949)
5313      45070F  ...          POINT (-97.775132 31.130337)

[5314 rows x 29 columns]

In [7]:
df_hospital_2['effectiveness_of_care_national_comparison_footnote']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
        ...
5309    22.0
5310    22.0
5311    22.0
5312    22.0
5313    22.0
Name: effectiveness_of_care_national_comparison_footnote, Length: 5314, dtype: float64

In [11]:
df_hospital_2['effectiveness_of_care_national_comparison_footnote'].describe()

count    2043.000000
mean       11.636809
std         6.709318
min         5.000000
25%         5.000000
50%        16.000000
75%        19.000000
max        22.000000
Name: effectiveness_of_care_national_comparison_footnote, dtype: float64

In [13]:
df_hospital_2['effectiveness_of_care_national_comparison_footnote'].isna().sum()

3271

In [15]:
df_hospital_2_nonull_effectiveness = df_hospital_2[~df_hospital_2['effectiveness_of_care_national_comparison_footnote'].isnull()]
df_hospital_2_nonull_effectiveness['effectiveness_of_care_national_comparison_footnote'].isna().sum()

0

In [16]:
dataframe_pivot = df_hospital_2_nonull_effectiveness.pivot_table(index=['state','city'],values=['effectiveness_of_care_national_comparison_footnote'],aggfunc='mean')

In [17]:
dataframe_pivot

                       effectiveness_of_care_national_comparison_footnote
state city
AK    ANCHORAGE                                                     19.0
      BARROW                                                         5.0
      CORDOVA                                                       16.0
      DILLINGHAM                                                    16.0
      Fort Wainwright                                               22.0
...                                                                  ...
WY    SUNDANCE                                                       5.0
      THERMOPOLIS                                                    5.0
      TORRINGTON                                                     5.0
      WHEATLAND                                                      5.0
      WORLAND                                                        5.0

[1742 rows x 1 columns]